version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  publish:
    jobs:
      - orb-tools/publish:
          orb-path: src/commit/orb.yml
          orb-ref: commitdev/circleci-orbs@dev:0.0.1
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true
